import { Zilla_Slab } from "next/font/google";
import "./globals.css";

const zilla_slab_init = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-zilla_slab",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zilla_slab_init.variable}>{children}</body>
    </html>
  );
}
